config/routes.rb
Rails.application.routes.draw do
  resources :books do 
    collection do
      get 'download_all'
    end
    member do
      get 'download'
    end
    resources :notes, except: :index  do 
      member do
        get 'download'
      end
    end
  end
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :notes, dependent: :destroy_async
  validates :title, 
    presence: true,
    length:{maximum: 127}, 
    uniqueness:{ scope: :user_id, case_sensitive: false, message: "title already exists!" }

  def global?
    is_global
  end

  def clear
    notes.destroy_all
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :list_notes, :download]

  include FilenameHelper
  
  # GET /books
  def index
    @books = current_user.books 
  end
  
  # GET /books/1
  def show
  end

  # GET /books/new
  def new
    @book = current_user.books.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    if @book.global?
      @book.clear
      redirect_to books_url, notice: 'Global book was successfully cleared.'
    else
      @book.destroy
      redirect_to books_url, notice: 'Book was successfully destroyed.'
    end
  end

  # DOWNLOAD /book/1/download
  def download 
    send_data book_as_zip(@book).string,
        filename: "#{sanitized_for_filename(@book.title)}.zip",
        type: "application/zip"
  end

  # DOWNLOAD /books/download_all
  def download_all 
    send_data books_as_zip(current_user.books).string,
        filename: "all_books.zip",
        type: "application/zip"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      begin
        @book = current_user.books.find(params[:id])
      rescue ActiveRecord::RecordNotFound => e
        redirect_to books_url, notice: "You don't own a book ##{params[:id]}."
      end
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title)
    end

    def book_as_zip(book)
      Zip::OutputStream.write_buffer do |stream|
        book.notes.each do |note|
          # add note to zip
          stream.put_next_entry("#{sanitized_for_filename(note.title)}.html")
          stream.write note.content_as_html.html_safe
        end  
      end
    end

    def books_as_zip(books)
      Zip::OutputStream.write_buffer do |stream|
        books.each do |book|
          book.notes.each do |note|
            # add note to zip
            stream.put_next_entry("#{sanitized_for_filename(book.title)}/#{sanitized_for_filename(note.title)}.html")
            stream.write note.content_as_html.html_safe
          end
        end  
      end
    end

  end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_notes.html.erb
<p>
    <strong>Book:</strong>
    <%= book.title %>
</p>
<% book.notes.each do |note| %>
    <div style="border-top: 1px solid lightgray;    margin: 20px;">
        <p>
            <strong>Note:</strong>
            <%= note.title %>
        </p>

        <p>
        <div style="border-top: 1px solid lightgray; padding: 20px;">
            <%= note.content_as_html.html_safe %>
        </div>

        </p>
    </div>
<% end %>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%#<div class="field"> %>
    <%#= form.label :user_id %>
    <%#= form.text_field :user_id %>
  <%#</div> %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>
<%= link_to 'Download all Books', download_all_books_path %></td>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= '<global>' if book.global? %></td>
        <td><%= book.title %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Download', download_book_path(book) %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to (book.global? ? 'Clear' : 'Destroy'), book, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<%#p>
  <strong>User:</strong>
  <%= @book.user_id %>
<%#/p%>

<p>
  <h1>Book: <%= @book.title %></h1>
  <br>
  
  <h3>Notes </h3>
  <br>
    
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @book.notes.each do |note| %>
        <tr>
          <td><%= note.title %></td>
          <td><%= note.content.size>8 ? note.content.first(5) + '...' : note.content.first(8)  %></td>
          <td><%= link_to 'Show', [@book ,note] %></td>
          <td><%= link_to 'Download', download_book_note_path(@book, note) %></td>
          <td><%= link_to 'Edit', edit_book_note_path(@book, note) %></td>
          <td><%= link_to 'Destroy', [@book ,note], method: :delete, data: { confirm: 'Are you sure?' } %></td>

        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Note', new_book_note_path(@book)%>

</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>